/*
 * gldf_unreal — GLDF → Datasmith exporter FFI surface.
 *
 * Generated by cbindgen from crates/gldf-unreal/src/ffi.rs.
 * DO NOT EDIT BY HAND. Regenerate via:
 *   cargo run -p gldf-unreal --bin gen-header
 */


#ifndef GLDF_UNREAL_H
#define GLDF_UNREAL_H

#include <stdint.h>
#include <stddef.h>

/*
 Layout MUST match `GldfUnrealOpts` in the generated C header. Any field
 reorder is a breaking ABI change.
 */
typedef struct GldfUnrealOpts {
  /*
   1 = centimetres (default), 0 = metres.
   */
  uint8_t units_cm;
  /*
   1 = copy MTL-referenced textures into the bundle.
   */
  uint8_t embed_textures;
  /*
   1 = apply GLDF MountingInfo offsets to the root Actor.
   */
  uint8_t apply_mounting;
  /*
   1 = overwrite an existing bundle directory.
   */
  uint8_t overwrite;
  /*
   Optional comma-separated variant id list. NULL = "all".
   */
  const char *variants_csv;
} GldfUnrealOpts;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Returns a pointer to a static NUL-terminated string with the crate
 version. The pointer is valid for the program's lifetime; do NOT free.
 */
const char *gldf_unreal_version(void);

/*
 Export `gldf_path` to `out_dir` using `opts`.

 On success returns 0 and leaves `*out_err = NULL`. On failure returns
 the error code (see the table in [`crate::ffi`]) and writes a
 Rust-owned, heap-allocated NUL-terminated UTF-8 string to `*out_err`;
 the C caller MUST free it via [`gldf_unreal_string_free`].

 # Safety
 All pointer arguments must be valid for their stated direction. The
 caller retains ownership of `gldf_path`, `out_dir`, `opts`, and
 `opts.variants_csv`.
 */
int32_t gldf_unreal_export(const char *gldf_path,
                           const char *out_dir,
                           const struct GldfUnrealOpts *opts,
                           char **out_err);

/*
 Return a JSON serialization of the most recent successful
 [`ExportReport`], or NULL if no export has run yet. Rust-owned string;
 free via [`gldf_unreal_string_free`].
 */
char *gldf_unreal_last_report_json(void);

/*
 Free a string previously returned through `out_err` or
 [`gldf_unreal_last_report_json`]. Passing NULL is a no-op.

 # Safety
 `s` must be a pointer previously returned by this library, or NULL.
 */
void gldf_unreal_string_free(char *s);

/*
 Load `gldf_path` and return the first variant's first non-emergency
 emitter's IES bytes (variant-resolved lumens/watts already patched).

 On success returns 0 and writes:
 - `*out_buf` = a Rust-allocated `u8` array; caller MUST free via
   [`gldf_unreal_bytes_free`] passing both the returned pointer AND
   the returned length.
 - `*out_len` = length in bytes.

 On failure returns the [`ExportError::code`] and writes a Rust-owned
 CString to `*out_err`; caller frees via [`gldf_unreal_string_free`].

 # Safety
 `gldf_path` must be a valid NUL-terminated UTF-8 C string.
 `out_buf`, `out_len`, `out_err` may be null individually — the caller
 loses access to that channel if it passes null.
 */
int32_t gldf_unreal_first_ies_bytes(const char *gldf_path,
                                    uint8_t **out_buf,
                                    uintptr_t *out_len,
                                    char **out_err);

/*
 Free a byte buffer previously returned by
 [`gldf_unreal_first_ies_bytes`] (or any future call documented to
 hand back a Rust-owned `u8*`). The caller MUST pass back exactly the
 pointer and length they received — using a different length is
 undefined behavior (we reconstruct a `Box<[u8]>` to drop it).

 # Safety
 `ptr` must be a pointer previously returned by this library, paired
 with the `len` it was returned with, or `ptr` may be NULL.
 */
void gldf_unreal_bytes_free(uint8_t *ptr, uintptr_t len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* GLDF_UNREAL_H */
