/*
 * gldf_unreal — GLDF → Datasmith exporter FFI surface.
 *
 * Generated by cbindgen from crates/gldf-unreal/src/ffi.rs.
 * DO NOT EDIT BY HAND. Regenerate via:
 *   cargo run -p gldf-unreal --bin gen-header
 */


#ifndef GLDF_UNREAL_H
#define GLDF_UNREAL_H

#include <stdint.h>
#include <stddef.h>

/*
 String-field selector for [`gldf_unreal_variant_string`].
 */
#define GLDF_VARIANT_FIELD_ID 0

#define GLDF_VARIANT_FIELD_PHOTOMETRY_ID 1

/*
 Layout MUST match `GldfUnrealOpts` in the generated C header. Any field
 reorder is a breaking ABI change.
 */
typedef struct GldfUnrealOpts {
  /*
   1 = centimetres (default), 0 = metres.
   */
  uint8_t units_cm;
  /*
   1 = copy MTL-referenced textures into the bundle.
   */
  uint8_t embed_textures;
  /*
   1 = apply GLDF MountingInfo offsets to the root Actor.
   */
  uint8_t apply_mounting;
  /*
   1 = overwrite an existing bundle directory.
   */
  uint8_t overwrite;
  /*
   Optional comma-separated variant id list. NULL = "all".
   */
  const char *variants_csv;
} GldfUnrealOpts;

/*
 Layout MUST match `GldfMeshHeader` in the generated C header.
 */
typedef struct GldfMeshHeader {
  uint32_t vertex_count;
  /*
   0 when the source OBJ has no `vn` lines.
   */
  uint32_t normal_count;
  /*
   0 when the source OBJ has no `vt` lines.
   */
  uint32_t uv_count;
  uint32_t polygon_count;
  /*
   Sum of all polygons' corner counts.
   */
  uint32_t corner_count;
  uint32_t material_group_count;
} GldfMeshHeader;

/*
 One face corner, flattened for C. `normal_idx` / `uv_idx` are -1 when
 the source face token had no normal / uv. `polygon_idx` says which
 polygon (0-based) this corner belongs to so the C++ side can rebuild
 the n-gon grouping without a second indirection array.
 */
typedef struct GldfMeshCorner {
  uint32_t position_idx;
  int32_t normal_idx;
  int32_t uv_idx;
  uint32_t polygon_idx;
} GldfMeshCorner;

/*
 One polygon: a contiguous run in the corners array + its material
 group index (into the per-handle material-group name list).
 */
typedef struct GldfMeshPolygon {
  uint32_t corner_offset;
  uint32_t corner_count;
  uint32_t material_group_idx;
} GldfMeshPolygon;

/*
 One resolved variant's scalar data. `*_present` flags distinguish
 "0" from "absent" for the optional photometric values.
 */
typedef struct GldfVariantInfo {
  int32_t lumens;
  uint8_t lumens_present;
  double watts;
  uint8_t watts_present;
  int32_t cct;
  uint8_t cct_present;
  uint32_t ies_len;
} GldfVariantInfo;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Returns a pointer to a static NUL-terminated string with the crate
 version. The pointer is valid for the program's lifetime; do NOT free.
 */
const char *gldf_unreal_version(void);

/*
 Export `gldf_path` to `out_dir` using `opts`.

 On success returns 0 and leaves `*out_err = NULL`. On failure returns
 the error code (see the table in [`crate::ffi`]) and writes a
 Rust-owned, heap-allocated NUL-terminated UTF-8 string to `*out_err`;
 the C caller MUST free it via [`gldf_unreal_string_free`].

 # Safety
 All pointer arguments must be valid for their stated direction. The
 caller retains ownership of `gldf_path`, `out_dir`, `opts`, and
 `opts.variants_csv`.
 */
int32_t gldf_unreal_export(const char *gldf_path,
                           const char *out_dir,
                           const struct GldfUnrealOpts *opts,
                           char **out_err);

/*
 Return a JSON serialization of the most recent successful
 [`ExportReport`], or NULL if no export has run yet. Rust-owned string;
 free via [`gldf_unreal_string_free`].
 */
char *gldf_unreal_last_report_json(void);

/*
 Free a string previously returned through `out_err` or
 [`gldf_unreal_last_report_json`]. Passing NULL is a no-op.

 # Safety
 `s` must be a pointer previously returned by this library, or NULL.
 */
void gldf_unreal_string_free(char *s);

/*
 Load `gldf_path` and return the first variant's first non-emergency
 emitter's IES bytes (variant-resolved lumens/watts already patched).

 On success returns 0 and writes:
 - `*out_buf` = a Rust-allocated `u8` array; caller MUST free via
   [`gldf_unreal_bytes_free`] passing both the returned pointer AND
   the returned length.
 - `*out_len` = length in bytes.

 On failure returns the [`ExportError::code`] and writes a Rust-owned
 CString to `*out_err`; caller frees via [`gldf_unreal_string_free`].

 # Safety
 `gldf_path` must be a valid NUL-terminated UTF-8 C string.
 `out_buf`, `out_len`, `out_err` may be null individually — the caller
 loses access to that channel if it passes null.
 */
int32_t gldf_unreal_first_ies_bytes(const char *gldf_path,
                                    uint8_t **out_buf,
                                    uintptr_t *out_len,
                                    char **out_err);

/*
 Free a byte buffer previously returned by
 [`gldf_unreal_first_ies_bytes`] (or any future call documented to
 hand back a Rust-owned `u8*`). The caller MUST pass back exactly the
 pointer and length they received — using a different length is
 undefined behavior (we reconstruct a `Box<[u8]>` to drop it).

 # Safety
 `ptr` must be a pointer previously returned by this library, paired
 with the `len` it was returned with, or `ptr` may be NULL.
 */
void gldf_unreal_bytes_free(uint8_t *ptr, uintptr_t len);

/*
 Open the first mesh of the first variant of the GLDF at `gldf_path`.

 On success returns a non-zero handle and fills `*out_header`. On
 failure returns 0 and writes a Rust-owned error string to `*out_err`
 (caller frees via [`gldf_unreal_string_free`]).

 The handle owns the parsed mesh until [`gldf_unreal_mesh_close`].

 # Safety
 `gldf_path` must be a valid NUL-terminated UTF-8 C string.
 `out_header` / `out_err` may individually be null.
 */
uint64_t gldf_unreal_first_mesh_open(const char *gldf_path,
                                     struct GldfMeshHeader *out_header,
                                     char **out_err);

/*
 Borrow read-only pointers into a handle's mesh arrays. Pointers stay
 valid until [`gldf_unreal_mesh_close`] on the same handle.

 `*out_normals` / `*out_uvs` are set to null when the source had no
 normals / UVs (`normal_count` / `uv_count` == 0 in the header).

 Returns 0 on success, non-zero if the handle is unknown.

 # Safety
 `handle` must be a live handle from [`gldf_unreal_first_mesh_open`].
 The out-pointers may individually be null (that channel is skipped).
 */
int32_t gldf_unreal_mesh_borrow(uint64_t handle,
                                const float **out_positions,
                                const float **out_normals,
                                const float **out_uvs,
                                const struct GldfMeshCorner **out_corners,
                                const struct GldfMeshPolygon **out_polygons);

/*
 Return the `group_idx`-th material-group name for a handle, as a
 Rust-owned CString (caller frees via [`gldf_unreal_string_free`]).
 Returns null if the handle or index is invalid.

 # Safety
 `handle` must be a live handle from [`gldf_unreal_first_mesh_open`].
 */
char *gldf_unreal_mesh_material_group(uint64_t handle, uint32_t group_idx);

/*
 Drop a mesh handle and free its arrays. No-op if the handle is unknown
 or zero.

 # Safety
 `handle` must be a handle from [`gldf_unreal_first_mesh_open`] or 0.
 */
void gldf_unreal_mesh_close(uint64_t handle);

/*
 Open the variant table for the GLDF at `gldf_path`. Resolves each
 variant's first non-emergency emitter's IES + photometric scalars.

 Returns a non-zero handle + writes `*out_variant_count` on success;
 0 + `*out_err` on failure. Free via [`gldf_unreal_variants_close`].

 # Safety
 `gldf_path` is a NUL-terminated UTF-8 C string; out-pointers may be null.
 */
uint64_t gldf_unreal_variants_open(const char *gldf_path,
                                   uint32_t *out_variant_count,
                                   char **out_err);

/*
 Fill `*out` with variant `idx`'s scalar data. Returns 0 on success,
 non-zero if the handle or index is invalid.

 # Safety
 `handle` must be live; `out` may be null.
 */
int32_t gldf_unreal_variant_info(uint64_t handle, uint32_t idx, struct GldfVariantInfo *out);

/*
 Return a string field (`GLDF_VARIANT_FIELD_*`) for variant `idx` as a
 Rust CString (caller frees via [`gldf_unreal_string_free`]). Null on
 invalid handle / index / field.

 # Safety
 `handle` must be live.
 */
char *gldf_unreal_variant_string(uint64_t handle, uint32_t idx, uint32_t field);

/*
 Borrow variant `idx`'s IES bytes. `*out_ptr` valid until close().
 Returns 0 on success, non-zero on invalid handle/index.

 # Safety
 `handle` must be live; out-pointers may be null.
 */
int32_t gldf_unreal_variant_ies(uint64_t handle,
                                uint32_t idx,
                                const uint8_t **out_ptr,
                                uint32_t *out_len);

/*
 Drop a variant-table handle. No-op on zero / unknown.

 # Safety
 `handle` must be from [`gldf_unreal_variants_open`] or 0.
 */
void gldf_unreal_variants_close(uint64_t handle);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* GLDF_UNREAL_H */
