// Editor-side scaffold that adds **File → Import → GLDF…** and routes
// the picked .gldf path through the Rust staticlib's
// `gldf_unreal_export()` call. Untested against UE 5.4 — first build
// will need verification; see crates/gldf-unreal/TESTING.md.

#include "GldfRsImporterModule.h"

#include "Logging/LogMacros.h"
#include "Misc/Paths.h"
#include "ToolMenus.h"
#include "Framework/Notifications/NotificationManager.h"
#include "Widgets/Notifications/SNotificationList.h"

// DesktopPlatform: native open/save dialogs.
#include "DesktopPlatformModule.h"
#include "IDesktopPlatform.h"

// The Rust C ABI header generated by `cargo run --bin gen-header`.
// Path is set up via PublicIncludePaths in GldfRsImporter.Build.cs.
extern "C" {
#include "gldf_unreal.h"
}

DEFINE_LOG_CATEGORY_STATIC(LogGldfRsImporter, Log, All);

#define LOCTEXT_NAMESPACE "GldfRsImporter"

void FGldfRsImporterModule::StartupModule()
{
    UE_LOG(LogGldfRsImporter, Log, TEXT("GldfRsImporter starting (Rust lib version: %hs)"),
        gldf_unreal_version());

    // Defer menu registration until ToolMenus is ready.
    UToolMenus::RegisterStartupCallback(
        FSimpleMulticastDelegate::FDelegate::CreateRaw(
            this, &FGldfRsImporterModule::RegisterMenus));
}

void FGldfRsImporterModule::ShutdownModule()
{
    UToolMenus::UnRegisterStartupCallback(this);
    UToolMenus::UnregisterOwner(this);
}

void FGldfRsImporterModule::RegisterMenus()
{
    FToolMenuOwnerScoped OwnerScoped(this);

    // Add to the main editor's File menu. The exact menu path may vary
    // by UE version; "MainFrame.MainMenu.File" is the documented hook
    // point in UE 5.x.
    UToolMenu* FileMenu = UToolMenus::Get()->ExtendMenu("MainFrame.MainMenu.File");
    if (!FileMenu)
    {
        UE_LOG(LogGldfRsImporter, Warning,
            TEXT("Could not find MainFrame.MainMenu.File — menu item not added."));
        return;
    }

    FToolMenuSection& Section = FileMenu->FindOrAddSection("FileImport");
    Section.AddMenuEntry(
        "ImportGldf",
        LOCTEXT("ImportGldf_Label", "Import GLDF…"),
        LOCTEXT("ImportGldf_Tooltip",
            "Convert a GLDF luminaire file to Datasmith and import it into the current level."),
        FSlateIcon(),
        FUIAction(FExecuteAction::CreateRaw(
            this, &FGldfRsImporterModule::OnImportGldfClicked))
    );
}

void FGldfRsImporterModule::OnImportGldfClicked()
{
    IDesktopPlatform* DesktopPlatform = FDesktopPlatformModule::Get();
    if (!DesktopPlatform)
    {
        UE_LOG(LogGldfRsImporter, Error, TEXT("DesktopPlatform unavailable."));
        return;
    }

    // 1. Pick a GLDF.
    TArray<FString> OpenFilenames;
    const bool bPicked = DesktopPlatform->OpenFileDialog(
        nullptr,
        TEXT("Pick a GLDF luminaire file"),
        FPaths::ProjectDir(),
        TEXT(""),
        TEXT("GLDF files (*.gldf)|*.gldf|All files (*.*)|*.*"),
        EFileDialogFlags::None,
        OpenFilenames);
    if (!bPicked || OpenFilenames.Num() == 0)
    {
        return;
    }
    const FString GldfPath = OpenFilenames[0];

    // 2. Pick an output directory.
    FString OutDir;
    const bool bDirPicked = DesktopPlatform->OpenDirectoryDialog(
        nullptr,
        TEXT("Output directory for the Datasmith bundle"),
        FPaths::ProjectIntermediateDir(),
        OutDir);
    if (!bDirPicked)
    {
        return;
    }

    // 3. Build the C opts struct. Defaults match the CLI's defaults.
    GldfUnrealOpts Opts = {};
    Opts.units_cm = 1;
    Opts.embed_textures = 0;
    Opts.apply_mounting = 0;
    Opts.overwrite = 1;
    Opts.variants_csv = nullptr;   // = "all"

    // 4. Call the Rust exporter.
    const FTCHARToUTF8 GldfPathUtf8(*GldfPath);
    const FTCHARToUTF8 OutDirUtf8(*OutDir);
    char* Err = nullptr;
    const int32 Code = gldf_unreal_export(
        GldfPathUtf8.Get(),
        OutDirUtf8.Get(),
        &Opts,
        &Err);

    if (Code == 0)
    {
        UE_LOG(LogGldfRsImporter, Log,
            TEXT("gldf_unreal_export OK → bundles written under %s"), *OutDir);

        // Optional toast.
        FNotificationInfo Info(FText::Format(
            LOCTEXT("ImportGldf_OK",
                "GLDF export complete. Datasmith bundle(s) written to:\n{0}\n\n"
                "Now use File → Import Into Level… on the .udatasmith file."),
            FText::FromString(OutDir)));
        Info.ExpireDuration = 8.0f;
        FSlateNotificationManager::Get().AddNotification(Info);
    }
    else
    {
        const FString ErrMsg = Err ? FString(UTF8_TO_TCHAR(Err)) : TEXT("(no message)");
        UE_LOG(LogGldfRsImporter, Error,
            TEXT("gldf_unreal_export failed (code %d): %s"), Code, *ErrMsg);

        FNotificationInfo Info(FText::Format(
            LOCTEXT("ImportGldf_Fail",
                "GLDF export failed (code {0}): {1}"),
            FText::AsNumber(Code),
            FText::FromString(ErrMsg)));
        Info.ExpireDuration = 12.0f;
        FSlateNotificationManager::Get().AddNotification(Info);

        if (Err)
        {
            gldf_unreal_string_free(Err);
        }
    }
}

#undef LOCTEXT_NAMESPACE

IMPLEMENT_MODULE(FGldfRsImporterModule, GldfRsImporter)
